# Generated by Django 5.0.6 on 2024-06-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chora_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraccount",
            name="folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chora_app.folder",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
